app
 name: spring-cloud-client

my:
 greeting: Hello world from config server
 list:
  values: One,Two,Three,Four

db:
  connection: config-server-connection-string-here
  host: 129.0.0.1
  port: 2400
